language: java
dist: Jammy
jdk:
  - openjdk8
branches:
  only:
    - master
    - develop

script:
  - mvn install:install-file -Dfile=res/jars/JSplashScreen.jar -DgroupId=com.thehowtotutorial.splashscreen -DartifactId=JSplashScreen -Dversion=1.0 -Dpackaging=jar
  - mvn -B package --file pom.xml
